services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    ports:
      - "8090:8090"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./config:/config
      - ~/Downloads:/downloads
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8090
    restart: unless-stopped
