services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    hostname: homeassistant
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=${TZ}
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    hostname: whisper
    command: --model small-int8 --language Spanish --data-dir /data
    volumes:
      - ./whisper:/data
    network_mode: host
    restart: unless-stopped

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    hostname: piper
    command: --voice es_MX-claude-high --data-dir /data
    volumes:
      - ./piper:/data
    network_mode: host
    restart: unless-stopped

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    hostname: openwakeword
    command: --preload-model hey_jarvis
    network_mode: host
    restart: unless-stopped
