services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    hostname: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3003:3000"
      - "3080:80"
      - "3443:443"
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./config/work:/opt/adguardhome/work
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
