services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/data
