services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    hostname: mattermost
    ports:
      - "8065:8065"
    volumes:
      - ./plugins:/mattermost/plugins
      - mattermost-data:/mattermost/data
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
      - MM_SERVICESETTINGS_ENABLERELIABLEWEBSOCKETS=true
      - TZ=${TZ}
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    restart: unless-stopped

volumes:
  mattermost-data:
