services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - OLLAMA_HOST=0.0.0.0:11434
      - ANTHROPIC_AUTH_TOKEN=ollama
      - ANTHROPIC_BASE_URL=http://localhost:11434
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    hostname: openwebui
    ports:
      - "3210:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - TZ=${TZ}
    depends_on:
      - ollama
    restart: unless-stopped
